### ISSUE TITLE
Is it intentional or by mistake?

### ISSUE THREAD

**Issue by sarbbottam** [sdras/JS-stroll#1]
Is it intentional or by mistake?

``` js
poL = document.createElementNS(svgNS, "viewBox"),
poL = document.createElementNS(svgNS, "polyline");
```

https://github.com/sdras/JS-stroll/blob/master/2-chapter-1-3-nature-of-code-in-js-svg/js/index.js#L7-L8

If intentional, could you add a comment with the rational.

Thanks!!

**Comment by sdras** [comment]
Mistake, I think I fixed that in the next pen but forgot to update the previous. Thanks!

**Comment by sdras** [comment]
fixed

**Comment by sarbbottam** [comment]
I am sure you know that you could have `fixed #issue-id` part of the `commit message` to close the issue automatically. Just a gentle reminder 😄
